### ISSUE TITLE
Missing async package in some Emacs versions

### ISSUE THREAD

**Issue by jgrzebyta** [ljos/sparql-mode#56]
I installed Emacs 25.1 from PPA `kelleyk/emacs` on **Linux Mint 18.1** and when installed sparql-mode (the latest) had error about missing `async` package. It was enough to install async through packages mode.

On the other side I have no such error in my Ubuntu installation on the other computer. I will give more details in a few days.

**Comment by ljos** [comment]
I forgot to remove the require. I have removed the dependency on the async package as the reason for using it got fixed in emacs proper.

Thank you for the report.

**Comment by ljos** [comment]
I looked over the kelleyk PPA and I don't think it was them who messed up. It is probably that on your ubuntu installation the async package was already installed by some other package or an older version of sparql-mode. Since I removed the dependency, but forgot to remove the require, and you installed on a new machine you didn't have the async package installed. That is why you got the error.
